baseURL = 'https://gmgoc.github.io/'
languageCode = 'en-GB'
title = 'Gwent MG Owners Club'
theme = ["dot-org-hugo-theme", "hugo-shortcode-gallery"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Gwent MG Owners Club â€” a friendly group of MG enthusiasts in South Wales"
  show_search = false
  custom_css = ["css/custom.css"]
  logo_on_white = "/img/gmgoc-logo-b.png"
  logo_on_black = "/img/gmgoc-logo-w.png"

[params.social_links]
  facebook = "https://www.facebook.com/groups/361716657894284"

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menus.main]]
  name = "Meetings"
  url = "/meetings/"
  weight = 20

[[menus.main]]
  name = "Join"
  url = "/join/"
  weight = 30

[[menus.main]]
  name = "Calendar"
  url = "/calendar/"
  weight = 40

[[menus.main]]
  name = "Contact"
  url = "/contact/"
  weight = 50

[[menus.main]]
  name = "Members"
  url = "/members/"
  weight = 60

[[menus.main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 70
